package org.firstinspires.ftc.robotcontroller.GMRCode.otherObjects;
public enum CurrentStates {

    STATEONE,
    STATETWO,
    STATETHREE,
    STATEFOUR,
    STATEFIVE,
    STATESIX,
    STATESEVEN,
    STATEEIGHT,
    STATENINE,
    STATETEN,
    STATEELEVEN,
    STATETWELVE,
    STATETHIRTEEN,

    FORWARD,
    BACKWARD,
    TURNRIGHT,
    TURNLEFT,
    STRAFELEFT,
    STRAFELEFT2,
    STRAFELEFT3,
    STRAFERIGHT,
    STRAFERIGHT2,
    DIAGONALUPRIGHT,
    DIAGONALUPLEFT,
    DIAGONALDOWNRIGHT,
    DIAGONALDOWNLEFT,

    ENCODERFORWARD,
    ENCODERFORWARD2,
    ENCODERBACKWARD,
    ENCODERBACKWARD2,
    ENCODERTURNRIGHT,
    ENCODERTURNLEFT,
    ENCODERSTRAFELEFT,
    ENCODERSTRAFERIGHT,
    ENCODERDIAGONALUPRIGHT,
    ENCODERDIAGONALUPLEFT,
    ENCODERDIAGONALDOWNRIGHT,
    ENCODERDIAGONALDOWNLEFT,

    COLOR,
    COLORFORWARD,
    COLORFORWARD2,
    COLORBACKWARD,
    COLORBACKWARD2,
    COLORTURNRIGHT,
    COLORTURNLEFT,
    COLORSTRAFELEFT,
    COLORSTRAFERIGHT,
    COLORDIAGONALUPRIGHT,
    COLORDIAGONALUPLEFT,
    COLORDIAGONALDOWNRIGHT,
    COLORDIAGONALDOWNLEFT,

    PROX,
    PROXFORWARD,
    PROXTURNRIGHT,
    PROXTURNLEFT,
    PROXSTRAFELEFT,
    PROXSTRAFERIGHT,
    PROXDIAGONALUPRIGHT,
    PROXDIAGONALUPLEFT,
    PROXDIAGONALDOWNRIGHT,
    PROXDIAGONALDOWNLEFT,

    GYRO,
    GYROTURNRIGHT,
    GYROTURNRIGHT2,
    GYROTURNLEFT,

    LAUNCH,

    DELAY,

    ELSE,

    PROGRAMEND,

    TEST,

    PUSHBEACON,
    PUSHBEACON2,

    STRAIGHTEN,

    ENCODERTURN,

    CHECKCOLOR,
    CHECKCOLOR2,

    FIXBEACON,
    FIXBEACON2,

    VUFORIA,
    VUFORIA2,
    VUFORIA3,
    VUFORIA4,
    VUFORIA5,
    VUFORIA6,

    VUFORIADRIVE,
    VUFORIADRIVE2
}